[package]
name = "rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
candid = "0.8.4"
ic-agent = "0.23.0"
ic-utils = "0.23.0"
tokio = { version = "1.25.0", features = ["full"] }
